TARGET=printints arith Mersenne 

all: $(TARGET)

printints: printints.c
	gcc -o printints -static printints.c

arith: arith.c
	gcc -o arith arith.c

Mersenne: Mersenne.c
	gcc -o Mersenne Mersenne.c

clean:
	rm $(TARGET)
